export const ActionTypes = {
    SET_TRANSLATION: 'SET_TRANSLATION',
    SET_TRANSLATION_NOT_FOUND_ERR: 'SET_TRANSLATION_NOT_FOUND_ERR',
    SET_LANGUAGE_NOT_FOUND_ERR: 'SET_LANGUAGE_NOT_FOUND_ERR',
    LOAD_TRANSLATION_FROM_API_ERR: 'LOAD_TRANSLATION_FROM_API_ERR',

    SET_GROUP: 'SET_GROUP',
    SET_GROUP_NOT_FOUND_ERR: 'SET_GROUP_NOT_FOUND_ERR',

    SET_VIEWED_NEWS_PIECE: 'SET_VIEWED_NEWS_PIECE',
    SET_VIEWED_NEWS_PIECE_NOT_FOUND_ERR: 'SET_VIEWED_NEWS_PIECE_NOT_FOUND_ERR',

    SET_ALL_NEWS: 'SET_ALL_NEWS',
    SET_ALL_NEWS_NOT_FOUND_ERR: 'SET_ALL_NEWS_NOT_FOUND_ERR',

    SET_VIEWED_TIMETABLE_DAY: 'SET_VIEWED_TIMETABLE_DAY',
    SET_VIEWED_TIMETABLE_DAY_NOT_FOUND_ERR: 'SET_VIEWED_TIMETABLE_DAY_NOT_FOUND_ERR',

    SET_INITIAL_SETUP: 'SET_INITIAL_SETUP',
};